IF OBJECT_ID('dbo.FIRST_NAME', 'FN') IS NOT NULL
    DROP FUNCTION dbo.FIRST_NAME;
GO

CREATE FUNCTION dbo.FIRST_NAME (@email VARCHAR(100))
RETURNS VARCHAR(50)
AS
BEGIN
    RETURN LEFT(@email, CHARINDEX('.', @email) - 1)
END;
GO

-- 5. Create LAST_NAME function
IF OBJECT_ID('dbo.LAST_NAME', 'FN') IS NOT NULL
    DROP FUNCTION dbo.LAST_NAME;
GO

CREATE FUNCTION dbo.LAST_NAME (@email VARCHAR(100))
RETURNS VARCHAR(50)
AS
BEGIN
    RETURN LEFT(SUBSTRING(@email, CHARINDEX('.', @email) + 1, 100), CHARINDEX('@', SUBSTRING(@email, CHARINDEX('.', @email) + 1, 100)) - 1)
END;
GO